-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 12:35:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DBTest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBTest` DEFAULT CHARACTER SET latin1 ;
USE `DBTest` ;

-- -----------------------------------------------------
-- Table `DBTest`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTest`.`client` (
  `idClient` INT(11) NOT NULL AUTO_INCREMENT,
  `nameClient` VARCHAR(45) NOT NULL,
  `cpfClient` VARCHAR(45) NOT NULL,
  `contactClient` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `cpfClient_UNIQUE` (`cpfClient` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
